### ISSUE TITLE
Legg til caching av spørringer

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-organization-bff#104]
~Sjekke ut [cachetools ](https://github.com/tkem/cachetools/) med en Time To Live (TTL) funksjons-cache,~

~eller [async-lru](https://pypi.org/project/async-lru/) for async/coroutines fra aiohttp-teamet.~

Sette opp nginx-cache i forkant av bff-en.

**Comment by valosnah** [comment]
Løses av:
https://github.com/Informasjonsforvaltning/fdk-ingress-config/pull/52
https://github.com/Informasjonsforvaltning/fdk-nginx-organization-bff/blob/main/nginx.conf
