### ISSUE TITLE
Fix all skipped tests

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-organization-bff#35]
Fix all skipped tests from the following two commits:

- [ ] https://github.com/Informasjonsforvaltning/fdk-organization-bff/commit/5bb524f2fa763256e4d46b114fc7cefe378b34c2

- [ ] https://github.com/Informasjonsforvaltning/fdk-organization-bff/commit/8df9d76291c8db2d26628d4db8302a8e0d1ed459

**Comment by azaxarov** [comment]
Won't fix
