### ISSUE TITLE
Organisasjoner vises ikke på virksomhetssiden

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-organization-bff#42]
Flere organisasjoner vises ikke på https://data.norge.no/organizations
Dette gjelder blant annet Ålesund, Molde og Sogndal kommune etter at de har fått byttet orgnr. ref https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/202

Relatert til #43 

Det ser også ut som om staging data blir bruk i prod. F.eks Avinor vises med 4 datasett i oversikten (samme som i staging), når man klikker inn på den har denne 9.

**Comment by valosnah** [comment]
Sparql-spørringen til organization-bff er ikke tilstrekkelig lenger, etter nødvendige endringer som ble gjort i dataset-catalog.
Det mangler foaf:Agent ressurs for enkelte dct:publisher. 

Kan potensielt fikses på to måter:
- Endre spørring til Elasticsearch (litt jobb i organization-bff)
- Federert sparql spørring (krever litt jobb i organization-catalog - mye jobb i organization-bff)

@lillelars @stigbd

**Comment by valosnah** [comment]
Ang staging data, det ser ut som sparql-spørringen til organization-bff ikke takler sameAs property.

**Comment by lillelars** [comment]
Forslag til løsning:

- [ ] For alle dct:publisher legg til trippler som beskriver registrert organisasjon (rov:RegisteredOrganization) inn i SPARQL service sin tripple store
- [ ] Oppdatere SPARQL spørringer i reportBFF og organizationBFF slik at de også spør etter rov:RegisteredOrganization

**Comment by KurtStian** [comment]
I tillegg er "antall datasett som er åpne feil". Når man er inne på https://data.norge.no/organizations/889640782 går det frem at det er 7 datsett som er åpne. Men når man klikker på den og kommer til søkesiden til FDK ser man at det finnes 22 åpne datasett.

**Comment by NilsOveTen** [comment]
@shenluna Er dette fortsatt et problem?

**Comment by shenluna** [comment]
@NilsOveTen Nei, nå vises organisasjonene på virksomhetssiden, men det er fremdeles et problem at tallene på oversikten over virksomheter og detaljesidene for virksomhetene ikke stemmer overens.

**Comment by shenluna** [comment]
Testet og verifisert
![image](https://user-images.githubusercontent.com/73637969/112612161-e362d400-8e1e-11eb-9175-6b1d5b5bbc86.png)
