### ISSUE TITLE
Virksomhetssiden og rapportsiden: Mangler riktig tall på datasett 

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-organization-bff#43]
Se f.eks digdir sin:
https://data.norge.no/organizations/991825827

- Disse tallene skal komme (minimum på sikt) fra organizationBFF

- [ ] PÅ virksomhetssiden:
![image](https://user-images.githubusercontent.com/39513382/110774382-06598980-825e-11eb-85eb-65b59e123123.png)
![image](https://user-images.githubusercontent.com/39513382/110774905-98fa2880-825e-11eb-85a3-ebef1e527f23.png)

- [ ] På rapportsiden:
![image](https://user-images.githubusercontent.com/39513382/110774513-2c7f2980-825e-11eb-8f5c-c279d9932158.png)

**Comment by KurtStian** [comment]
Se kommentar: https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/42#issuecomment-806473213

**Comment by shenluna** [comment]
Disse vises nå riktig i prod.
![image](https://user-images.githubusercontent.com/73637969/112612064-caf2b980-8e1e-11eb-8af3-7303519b2100.png)
