### ISSUE TITLE
Oppdatere SPARQL spørringer for organizationBFF

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-organization-bff#45]
Se issue:
https://github.com/informasjonsforvaltning/fdk-organization-bff/issues/42

NB! Bør også sjekke om organizationBFF spør reportsBFF - dette er uheldig i så fall. De bør være separate spørringer.

Relatert til https://github.com/Informasjonsforvaltning/fdk-reports-bff/issues/52
- [ ] Spørringer på virksomhetssiden skal være likt som antallet på rapportsiden (og i portal).
![image](https://user-images.githubusercontent.com/39513382/112109485-f15fed00-8bb1-11eb-94d9-325b7f05f5ba.png)

- [ ] Spørringer på virksomhetssiden skal være likt som antallet på rapportsiden (og i portal).
![image](https://user-images.githubusercontent.com/39513382/112109572-09d00780-8bb2-11eb-8745-da201f082970.png)

**Comment by shenluna** [comment]
Testet OK i Stag.
