### ISSUE TITLE
Spørringen mot fdk-metadata-quality-service manger NAP filter

### ISSUE THREAD

**Issue by azaxarov** [Informasjonsforvaltning/fdk-organization-bff#65]
Manglende NAP filter for Transportportal konteksten gjør at catalog rating får en feil verdi.

Eksempel: https://nap.staging.fellesdatakatalog.digdir.no/organizations/910244132/datasets

Rating skal være 48%, men er 35%.

<img width="1180" alt="Screenshot 2021-05-06 at 13 09 05" src="https://user-images.githubusercontent.com/29962353/117289438-dea52d00-ae6c-11eb-9f62-5815a0682f42.png">
<img width="1159" alt="Screenshot 2021-05-06 at 13 08 58" src="https://user-images.githubusercontent.com/29962353/117289433-dbaa3c80-ae6c-11eb-9912-e73b71410bb8.png">

**Comment by shenluna** [comment]
Testet og verifisert
![image](https://user-images.githubusercontent.com/73637969/117415811-03ef7500-af19-11eb-96af-0d67db1ba352.png)
